spring.application.name=Job-Portal

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb\://localhost\:27017/jobportal

USER_FOUND = User has registered already.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS = Invalid Credentials
OTP_NOT_FOUND = OTP is expired.
OTP_INCORRECT = OTP is incorrect.
JOB_NOT_FOUND = Job not found
JOB_APPLIED_ALREADY = Job applied already.


# Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mantukumar4376@gmail.com
spring.mail.password=hwmvkvmtzfndauau
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


# A secure base64 encoded key for JWT. You can generate one online.
# Example: 
# Using command line: echo 'your-secret-key-of-at-least-256-bits' | base64
# Or use an online tool to generate a secure base64 key
jwt.secret=S_bYjO0Sg3h_8x9M3KjF6d7a2Z5tH0wD1z_2x4c9V5b7N3m6P8qR
# Token validity in seconds. 86400 seconds = 24 hours.
jwt.token.validity=86400
